---

steps:
  build:
    image: moanos/sphinx-rtd
    commands:
      - cd docs && make html

    when:
      event: [ tag, push ]

  deploy:
    image: appleboy/drone-scp
    settings:
      strip_components: 3
      host:
        from_secret: host
      username:
        from_secret: ssh_user
      target:
        from_secret: path
      source: docs/_build/html/
      key:
        from_secret: ssh_key
    when:
      event: [ tag, push ]



